import type { Metadata } from "next";
import { Inter, Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import { MainHeader, MainNavbar } from "./_components/modules";

const inter = Be_Vietnam_Pro({
  weight: "300",
  subsets: ["vietnamese", "latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="page">
          <header>
            <MainHeader />
          </header>
          <main>
            <nav>
              <MainNavbar />
            </nav>
            <article>{children}</article>
          </main>
        </div>
      </body>
    </html>
  );
}
